class areaCities {
	constructor(){
		this.area_city = [ 
			//area
			"South",
			"Center",
			"North",
			//cities
			"Jerusalem",
			"Tel Aviv",
			"Haifa",
			"Petah Tikva",
			"Ashdod",
			"Netanya",
			"Beersheba",
			"Bnei Brak",
			"Holon",
			"Ramat Gan",
			"Rehovot",
			"Ashkelon",
			"Bat Yam",
			"Beit Shemesh",
			"Kfar Saba",
			"Herzliya",
			"Hadera",
			"Modi'in-Maccabim-Re'ut",
			"Nazareth",
			"Ramla",
			"Lod",
			"Hod HaSharon",
			"Givatayim",
			"Kiryat Atav",
			"Nahariya",
			"Kiryat Gat",
			"Eilat",
			"Rosh Haayin",
			"Afula",
			"Nes Ziona",
			"El'ad",
			"Ramat Hasharon",
			"Yavne",
			"Tiberias",
			"Tayibe",
			"Kiryat Bialik",
			"Kiryat Ono",
			"Ma'ale Adumim",
			"Or Yehuda",
			"Safed",
			"Netivot",
			"Dimona",
			"Sakhnin",
			"Yehud-Monosson",
			"Ofakim",
			"Giv'at Shmuel",
			"Migdal Haemek",
			"Sderot",
			"Rishon Lezion",
			"Nesher",
			"Kiryat Shmona",
			"Yokneam Illit",
			"Kiryat Malakhi",
			"Ariel",
			"Or Akiva",
			"Beit She'an",
			"Ra'anana",
			"Kiryat Yam",
			"Arad",
		];
};
	
} 

module.exports = new areaCities();
